"""Add clicked column to NewsRead

Revision ID: 9a5acad0d6bc
Revises: d66f78c7c7b4
Create Date: 2024-02-01 00:24:10.721676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5acad0d6bc'
down_revision = 'd66f78c7c7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_read', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_read', schema=None) as batch_op:
        batch_op.drop_column('clicked')

    # ### end Alembic commands ###
